version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - whattodo
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www/symfony
            - ./var:/var/www/symfony/var
            - ./vendor:/var/www/symfony/vendor
        networks:
            - whattodo
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - .:/var/www/symfony
            - ./var:/var/www/symfony/var
            - ./vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - whattodo
volumes:
    db_app:    
networks:
    whattodo: